-- Home-page instruments: official prints for AGS, household credit, people, housing.
-- Extends public_dashboard_metric so anon can read the tape.

create or replace function public_dashboard_metric(mid text)
returns boolean
language sql
immutable
parallel safe
set search_path = public
as $$
  select mid = any (array[
    'rba_hike_prob_market_au',
    'rba_hold_prob_market_au',
    'rba_cut_prob_market_au',
    'rba_hike_prob_fundamentals_au',
    'rba_hold_prob_fundamentals_au',
    'rba_cut_prob_fundamentals_au',
    'asx_ib_implied_yield_au',
    'cash_rate_au',
    'bond_yield_10y_au',
    'cpi_annual_au',
    'cpi_index_au',
    'wpi_annual_au',
    'inflation_rate',
    'real_wage_growth',
    'avg_wage_ppp',
    'credit_housing_12m_au',
    'household_debt_income_au',
    'household_debt_to_income',
    'household_savings_rate',
    'years_to_buy_home',
    'gdp_per_capita',
    'gdp_nominal_usd',
    'population',
    'productivity_level',
    'productivity_growth_10y',
    'government_debt_gdp',
    'unemployment_rate',
    'ags_face_value_bn',
    'ags_interest_payments_bn',
    'gst_receipts_bn',
    'gdp_nominal_aud_bn',
    'household_credit_bn',
    'erp_persons',
    'nom_annual',
    'natural_increase_annual',
    'population_growth_annual',
    'dwelling_completions',
    'dwelling_stock_value_bn',
    'mean_dwelling_price'
  ]);
$$;

insert into metrics (
  metric_id, name, unit, basis, direction, category,
  source_tier, source_org, source_dataset, source_url, source_published, period
) values
  ('ags_face_value_bn', 'Australian Government Securities on issue', 'AUD billion',
   'Face value of AGS, not net debt and not market value', 'higher_is_more_pressure', 'fiscal',
   1, 'Australian Office of Financial Management', 'AGS on issue',
   'https://www.aofm.gov.au/publications/speeches/opening-statement-economics-legislation-committee-1', '2026-02-11', '2026-02-11'),
  ('ags_interest_payments_bn', 'Interest payments on AGS', 'AUD billion',
   'Cash interest payments on Australian Government Securities, Budget Paper 1', 'higher_is_more_pressure', 'fiscal',
   1, 'Australian Government', 'Budget Paper No. 1, Table 6.9',
   'https://archive.budget.gov.au/2025-26/bp1/download/bp1_bs-6.pdf', '2025-03', '2025-26'),
  ('gst_receipts_bn', 'GST receipts', 'AUD billion',
   'GST receipts, Budget Paper No. 3', 'neutral', 'fiscal',
   1, 'Australian Government', 'Budget Paper No. 3, GST',
   'https://archive.budget.gov.au/2025-26/bp3/download/bp3_13_part_3.pdf', '2025-03', '2025-26'),
  ('gdp_nominal_aud_bn', 'Nominal GDP', 'AUD billion',
   'Implied from Budget Paper 1 total receipts as a share of GDP', 'neutral', 'economy',
   1, 'Australian Government', 'Budget Paper No. 1 receipts as per cent of GDP',
   'https://archive.budget.gov.au/2025-26/bp1/download/bp1_bs-4.pdf', '2025-03', '2025-26'),
  ('household_credit_bn', 'Household credit outstanding', 'AUD billion',
   'RBA Lending and Credit Aggregates D2, household credit, monthly', 'higher_is_more_pressure', 'households',
   1, 'Reserve Bank of Australia', 'Statistical table D2',
   'https://www.rba.gov.au/statistics/tables/xls/d02hist.xlsx', '2026-06', '2026-06'),
  ('erp_persons', 'Estimated resident population', 'persons',
   'ABS estimated resident population at quarter end', 'neutral', 'people',
   1, 'Australian Bureau of Statistics', 'National, state and territory population',
   'https://www.abs.gov.au/statistics/people/population/national-state-and-territory-population/latest-release', '2025-12', '2025-12-31'),
  ('nom_annual', 'Net overseas migration', 'persons',
   'Year ended December, ABS preliminary', 'neutral', 'people',
   1, 'Australian Bureau of Statistics', 'National, state and territory population',
   'https://www.abs.gov.au/statistics/people/population/national-state-and-territory-population/latest-release', '2025-12', '2025'),
  ('natural_increase_annual', 'Natural increase', 'persons',
   'Births minus deaths, year ended December, ABS preliminary', 'neutral', 'people',
   1, 'Australian Bureau of Statistics', 'National, state and territory population',
   'https://www.abs.gov.au/statistics/people/population/national-state-and-territory-population/latest-release', '2025-12', '2025'),
  ('population_growth_annual', 'Population growth', 'persons',
   'Year ended December, ABS preliminary', 'neutral', 'people',
   1, 'Australian Bureau of Statistics', 'National, state and territory population',
   'https://www.abs.gov.au/statistics/people/population/national-state-and-territory-population/latest-release', '2025-12', '2025'),
  ('dwelling_completions', 'Dwelling completions', 'dwellings',
   'Total sector dwelling completions, seasonally adjusted', 'neutral', 'housing',
   1, 'Australian Bureau of Statistics', 'Building Activity, Australia',
   'https://www.abs.gov.au/statistics/industry/building-and-construction/building-activity-australia/dec-2025', '2025-12', '2025-Q4'),
  ('dwelling_stock_value_bn', 'Total value of residential dwellings', 'AUD billion',
   'ABS Total Value of Dwellings, Australia', 'higher_is_more_pressure', 'housing',
   1, 'Australian Bureau of Statistics', 'Total Value of Dwellings',
   'https://www.abs.gov.au/media-centre/media-releases/value-dwellings-falls-03', '2026-06', '2026-Q2'),
  ('mean_dwelling_price', 'Mean dwelling price', 'AUD',
   'ABS mean price of residential dwellings, Australia', 'higher_is_more_pressure', 'housing',
   1, 'Australian Bureau of Statistics', 'Total Value of Dwellings',
   'https://www.abs.gov.au/media-centre/media-releases/value-dwellings-falls-03', '2026-06', '2026-Q2')
on conflict (metric_id) do update set
  name = excluded.name,
  unit = excluded.unit,
  basis = excluded.basis,
  source_url = excluded.source_url,
  source_published = excluded.source_published,
  period = excluded.period;

insert into observations (metric_id, entity, period, value, status) values
  ('ags_face_value_bn', 'AUS', '2023-06-30', 889.8, 'published'),
  ('ags_face_value_bn', 'AUS', '2024-06-30', 906.9, 'published'),
  ('ags_face_value_bn', 'AUS', '2026-02-11', 994.4, 'published'),
  ('ags_interest_payments_bn', 'AUS', '2024-25', 22.666, 'published'),
  ('ags_interest_payments_bn', 'AUS', '2025-26', 26.303, 'published'),
  ('gst_receipts_bn', 'AUS', '2024-25', 89.4, 'published'),
  ('gst_receipts_bn', 'AUS', '2025-26', 94.234, 'published'),
  ('gdp_nominal_aud_bn', 'AUS', '2024-25', 2782, 'derived'),
  ('gdp_nominal_aud_bn', 'AUS', '2025-26', 2884, 'derived'),
  ('household_credit_bn', 'AUS', '2025-11', 2469.49, 'published'),
  ('household_credit_bn', 'AUS', '2025-12', 2487.29, 'published'),
  ('household_credit_bn', 'AUS', '2026-01', 2497.93, 'published'),
  ('household_credit_bn', 'AUS', '2026-02', 2508.16, 'published'),
  ('household_credit_bn', 'AUS', '2026-03', 2522.64, 'published'),
  ('household_credit_bn', 'AUS', '2026-04', 2536.04, 'published'),
  ('household_credit_bn', 'AUS', '2026-05', 2549.34, 'published'),
  ('household_credit_bn', 'AUS', '2026-06', 2568.43, 'published'),
  ('erp_persons', 'AUS', '2025-06-30', 27614411, 'published'),
  ('erp_persons', 'AUS', '2025-12-31', 27801023, 'published'),
  ('nom_annual', 'AUS', '2022', 437857, 'published'),
  ('nom_annual', 'AUS', '2023', 530620, 'published'),
  ('nom_annual', 'AUS', '2024', 330458, 'published'),
  ('nom_annual', 'AUS', '2025', 300955, 'published'),
  ('natural_increase_annual', 'AUS', '2022', 108633, 'published'),
  ('natural_increase_annual', 'AUS', '2023', 105755, 'published'),
  ('natural_increase_annual', 'AUS', '2024', 101411, 'published'),
  ('natural_increase_annual', 'AUS', '2025', 111539, 'published'),
  ('population_growth_annual', 'AUS', '2022', 546490, 'published'),
  ('population_growth_annual', 'AUS', '2023', 636375, 'published'),
  ('population_growth_annual', 'AUS', '2024', 431869, 'published'),
  ('population_growth_annual', 'AUS', '2025', 412494, 'published'),
  ('dwelling_completions', 'AUS', '2024-Q4', 45167, 'published'),
  ('dwelling_completions', 'AUS', '2025-Q1', 43517, 'published'),
  ('dwelling_completions', 'AUS', '2025-Q2', 40524, 'published'),
  ('dwelling_completions', 'AUS', '2025-Q3', 44242, 'published'),
  ('dwelling_completions', 'AUS', '2025-Q4', 43536, 'published'),
  ('dwelling_stock_value_bn', 'AUS', '2021-Q2', 8726, 'published'),
  ('dwelling_stock_value_bn', 'AUS', '2021-Q3', 9326, 'published'),
  ('dwelling_stock_value_bn', 'AUS', '2021-Q4', 9914, 'published'),
  ('dwelling_stock_value_bn', 'AUS', '2022-Q1', 10094, 'published'),
  ('dwelling_stock_value_bn', 'AUS', '2022-Q2', 10029, 'published'),
  ('dwelling_stock_value_bn', 'AUS', '2022-Q3', 9730, 'published'),
  ('dwelling_stock_value_bn', 'AUS', '2022-Q4', 9773, 'published'),
  ('dwelling_stock_value_bn', 'AUS', '2023-Q1', 9803, 'published'),
  ('dwelling_stock_value_bn', 'AUS', '2023-Q2', 10102, 'published'),
  ('dwelling_stock_value_bn', 'AUS', '2023-Q3', 10253, 'published'),
  ('dwelling_stock_value_bn', 'AUS', '2023-Q4', 10564, 'published'),
  ('dwelling_stock_value_bn', 'AUS', '2024-Q1', 10736, 'published'),
  ('dwelling_stock_value_bn', 'AUS', '2024-Q2', 11000, 'published'),
  ('dwelling_stock_value_bn', 'AUS', '2024-Q3', 11053, 'published'),
  ('dwelling_stock_value_bn', 'AUS', '2024-Q4', 11319, 'published'),
  ('dwelling_stock_value_bn', 'AUS', '2025-Q1', 11409, 'published'),
  ('dwelling_stock_value_bn', 'AUS', '2025-Q2', 11697, 'published'),
  ('dwelling_stock_value_bn', 'AUS', '2025-Q3', 11978, 'published'),
  ('dwelling_stock_value_bn', 'AUS', '2025-Q4', 12509, 'published'),
  ('dwelling_stock_value_bn', 'AUS', '2026-Q1', 12723, 'published'),
  ('dwelling_stock_value_bn', 'AUS', '2026-Q2', 12689, 'published'),
  ('mean_dwelling_price', 'AUS', '2026-Q2', 1100000, 'published')
on conflict (metric_id, entity, period) do update set
  value = excluded.value,
  status = excluded.status;
