/**
 * World Bank WDI indicators. Maps to existing metrics where possible and adds
 * history for denominator-flip / step-change detectors.
 * API: https://api.worldbank.org/v2/
 */
export const WB_SERIES = [
  // Rates for showing US-dollar figures in national currency (the dashboards read Australia's: A$ per US$). Each
  // US$ figure is converted with the rate of its own year: the average exchange rate for market US$ (IMF, World
  // Bank), the household-consumption PPP for OECD How's Life? money figures, the GDP PPP for GDP at PPP.
  {
    metric_id: 'fx_lcu_per_usd',
    indicator: 'PA.NUS.FCRF',
    name: 'Official exchange rate, national currency per US$ (annual average)',
    unit: 'national currency per USD',
    basis: 'Official exchange rate, period average, annual',
    direction: 'neutral',
    category: 'exchange_rates',
    source_id: 'worldbank_wdi',
    source_dataset: 'WDI PA.NUS.FCRF',
    startYear: 1990,
  },
  {
    metric_id: 'ppp_lcu_hfce',
    indicator: 'PA.NUS.PRVT.PP',
    name: 'Purchasing power parity for household final consumption, national currency per international $',
    unit: 'national currency per international dollar',
    basis: 'PPP conversion factor, households and NPISHs final consumption expenditure, annual',
    direction: 'neutral',
    category: 'exchange_rates',
    source_id: 'worldbank_wdi',
    source_dataset: 'WDI PA.NUS.PRVT.PP',
    startYear: 1990,
  },
  {
    metric_id: 'ppp_lcu_gdp',
    indicator: 'PA.NUS.PPP',
    name: 'Purchasing power parity for GDP, national currency per international $',
    unit: 'national currency per international dollar',
    basis: 'PPP conversion factor, GDP, annual',
    direction: 'neutral',
    category: 'exchange_rates',
    source_id: 'worldbank_wdi',
    source_dataset: 'WDI PA.NUS.PPP',
    startYear: 1990,
  },
  // Full history for the GDP-per-person bar race (The Indices). The dashboards keep the IMF WEO figure (gdp_per_capita).
  {
    metric_id: 'gdp_per_capita_usd_wb',
    indicator: 'NY.GDP.PCAP.CD',
    name: 'GDP per capita (current US$)',
    unit: 'USD',
    basis: 'Gross domestic product per person, current US dollars, annual',
    direction: 'higher_is_less_pressure',
    category: 'economy',
    source_id: 'worldbank_wdi',
    source_dataset: 'WDI NY.GDP.PCAP.CD',
    startYear: 1960,
  },
  {
    metric_id: 'market_cap_gdp',
    indicator: 'CM.MKT.LCAP.GD.ZS',
    name: 'Stock market capitalisation',
    unit: 'percent of GDP',
    basis: 'Listed domestic companies, annual',
    direction: 'higher_is_less_pressure',
    category: 'markets',
    source_id: 'worldbank_wdi',
    source_dataset: 'WDI CM.MKT.LCAP.GD.ZS',
    startYear: 2000,
  },
  {
    metric_id: 'population',
    indicator: 'SP.POP.TOTL',
    name: 'Total population',
    unit: 'persons',
    basis: 'Mid-year population, annual',
    direction: 'neutral',
    category: 'demography',
    source_id: 'worldbank_wdi',
    source_dataset: 'WDI SP.POP.TOTL',
    startYear: 2000,
  },
  {
    metric_id: 'gdp_nominal_usd',
    indicator: 'NY.GDP.MKTP.CD',
    name: 'GDP (nominal)',
    unit: 'USD',
    basis: 'Current US dollars, annual',
    direction: 'higher_is_less_pressure',
    category: 'economy',
    source_id: 'worldbank_wdi',
    source_dataset: 'WDI NY.GDP.MKTP.CD',
    startYear: 2000,
  },
  {
    metric_id: 'inflation_wb',
    indicator: 'FP.CPI.TOTL.ZG',
    name: 'Consumer price inflation',
    unit: 'percent',
    basis: 'Annual CPI change, World Bank WDI',
    direction: 'higher_is_more_pressure',
    category: 'prices',
    source_id: 'worldbank_wdi',
    source_dataset: 'WDI FP.CPI.TOTL.ZG',
    startYear: 2000,
  },
  {
    metric_id: 'unemployment_rate',
    indicator: 'SL.UEM.TOTL.ZS',
    name: 'Unemployment rate',
    unit: 'percent of labour force',
    basis: 'ILO estimate, annual',
    direction: 'higher_is_more_pressure',
    category: 'labour',
    source_id: 'worldbank_wdi',
    source_dataset: 'WDI SL.UEM.TOTL.ZS',
    startYear: 2000,
  },
  {
    metric_id: 'government_debt_gdp',
    indicator: 'GC.DOD.TOTL.GD.ZS',
    name: 'Central government debt',
    unit: 'percent of GDP',
    basis: 'Central government, gross debt, annual',
    direction: 'higher_is_more_pressure',
    category: 'fiscal',
    source_id: 'worldbank_wdi',
    source_dataset: 'WDI GC.DOD.TOTL.GD.ZS',
    startYear: 2000,
  },
];
