/**
 * Bar-chart-race videos for The Indices: 9:16, 16:9 and 1:1, music bed with captions, published as a visual.
 *
 *   npx tsx --import ./scripts/node-shims.mjs scripts/render-races.ts --list       # every race and when it last ran
 *   npx tsx --import ./scripts/node-shims.mjs scripts/render-races.ts --dry-run    # render the next race to drafts/; publish nothing
 *   npx tsx --import ./scripts/node-shims.mjs scripts/render-races.ts              # render, upload and publish the next race
 *   VISUAL_KEY=race:erp_cob ... render-races.ts                                    # a particular race
 *
 * Runs on the GitHub runner (agent.yml, task races): a render needs Chrome and minutes. Captions come from the data
 * (lib/visuals-race.ts), so there are no model-written claims to check. Music is generated by ElevenLabs (cleared for
 * commercial use); if that fails the videos go out with captions only.
 */
import { copyFile, mkdir, mkdtemp, readFile, rm, stat, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { bundle } from '@remotion/bundler';
import { ensureBrowser, renderMedia, renderStill, selectComposition } from '@remotion/renderer';
import { createClient } from '@/lib/supabase-server';
import { ELEVEN_API_BASE } from '@/lib/elevenlabs-client';
import { buildRaces, type Race } from '@/lib/visuals-race';
import { HOLD_SECONDS, INTRO_SECONDS, RACE_COMPOSITION_ID, RACE_FPS, raceSeconds, stepSeconds, type RaceFormat, type RaceProps } from '@/lib/race-video-types';
import { FONT_FILES } from '@/remotion/fonts';
import { fetchHouseTrack } from '@/lib/house-track';
import { enqueue, queueEnabled, scheduleContent } from '@/lib/content-queue';
import { postSocial } from '@/lib/social-post';

const WEB_ROOT = resolve(__dirname, '..');
const BUCKET = 'visual-videos';
const FORMATS: RaceFormat[] = ['9:16', '16:9', '1:1'];
const COOLDOWN_DAYS = 28;
const args = process.argv.slice(2);
const dry = args.includes('--dry-run');
const list = args.includes('--list');
const forced = process.env.VISUAL_KEY?.trim() || null;
/** Re-render a published race in place (same page, new videos and poster), e.g. after the house track changed. */
const replace = args.includes('--replace') || process.env.RACE_REPLACE === 'true';

let musicIsHouse = false;

/** The house track; before one is chosen, a licence-cleared bed from ElevenLabs Music; else null (captions only). */
async function music(seconds: number, publicDir: string): Promise<string | null> {
  const house = await fetchHouseTrack(publicDir, 'music.mp3');
  if (house) { console.log('Music: the house track.'); musicIsHouse = true; return house; }
  const key = process.env.ELEVENLABS_API_KEY;
  if (!key) { console.log('No ELEVENLABS_API_KEY: captions only.'); return null; }
  try {
    const res = await fetch(`${ELEVEN_API_BASE}/v1/music`, {
      method: 'POST',
      headers: { 'xi-api-key': key, 'content-type': 'application/json', accept: 'audio/mpeg' },
      body: JSON.stringify({
        prompt: 'Upbeat, modern instrumental for a data visualisation video: light electronic percussion, warm synth pads, steady build, no vocals, clean ending.',
        music_length_ms: Math.round(seconds * 1000),
        model_id: 'music_v1',
      }),
      signal: AbortSignal.timeout(180_000),
    });
    if (!res.ok) { console.log(`Music not generated (${res.status}: ${(await res.text()).slice(0, 160)}): captions only.`); return null; }
    await writeFile(join(publicDir, 'music.mp3'), Buffer.from(await res.arrayBuffer()));
    console.log('Music generated.');
    return 'music.mp3';
  } catch (e) {
    console.log(`Music not generated (${(e as Error).message}): captions only.`);
    return null;
  }
}

async function render(race: Race, musicFile: string | null, publicDir: string, outDir: string): Promise<Record<string, string>> {
  await mkdir(join(publicDir, 'fonts'), { recursive: true });
  for (const f of FONT_FILES) await copyFile(join(WEB_ROOT, 'app', 'fonts', f), join(publicDir, 'fonts', f));
  const browserExecutable = process.env.REMOTION_BROWSER?.trim() || undefined;
  if (!browserExecutable) await ensureBrowser();
  console.log('Bundling…');
  const serveUrl = await bundle({
    entryPoint: join(WEB_ROOT, 'remotion', 'index.ts'),
    publicDir,
    webpackOverride: (config) => ({ ...config, resolve: { ...config.resolve, alias: { ...((config.resolve?.alias as Record<string, string> | undefined) ?? {}), '@': WEB_ROOT } } }),
  });
  const out: Record<string, string> = {};
  for (const format of FORMATS) {
    const props: RaceProps = { race, format, musicFile };
    const composition = await selectComposition({ serveUrl, id: RACE_COMPOSITION_ID, inputProps: props, browserExecutable });
    const file = join(outDir, `${format.replace(':', 'x')}.mp4`);
    console.log(`Rendering ${format}: ${composition.width}x${composition.height}, ${composition.durationInFrames} frames…`);
    let tenth = -1;
    await renderMedia({
      composition, serveUrl, codec: 'h264', crf: 20, outputLocation: file, inputProps: props, browserExecutable, timeoutInMilliseconds: 120_000,
      onProgress: ({ progress }) => { const t = Math.floor(progress * 10); if (t !== tenth) { tenth = t; process.stdout.write(` ${t * 10}%`); } },
    });
    console.log(`\n  ${file} (${((await stat(file)).size / 1e6).toFixed(1)} MB)`);
    out[format] = file;
  }
  // The poster: the square frame at the final standings (before the end card), shown with a play mark on the site.
  const props: RaceProps = { race, format: '1:1', musicFile: null };
  const composition = await selectComposition({ serveUrl, id: RACE_COMPOSITION_ID, inputProps: props, browserExecutable });
  const n = race.frames.length;
  const frame = Math.round((INTRO_SECONDS + stepSeconds(n) * (n - 1) + HOLD_SECONDS / 2) * RACE_FPS);
  out.poster = join(outDir, 'poster.jpg');
  await renderStill({ composition, serveUrl, output: out.poster, frame, inputProps: props, imageFormat: 'jpeg', jpegQuality: 88, browserExecutable });
  console.log(`  ${out.poster} (frame ${frame})`);
  return out;
}

const slugify = (t: string) => t.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 70);

async function main() {
  const db = createClient();
  const races = await buildRaces();
  // Races queued but not yet out count as made, so the same race isn't rendered again while it waits.
  const { data: made } = await db.from('visuals').select('dataset_key, published_at, created_at').eq('template', 'race').in('status', ['published', 'draft']);
  const past = (made ?? []).map((v) => ({ dataset_key: v.dataset_key, at: v.published_at ?? v.created_at })).sort((a, b) => b.at.localeCompare(a.at));
  const last = new Map<string, number>();
  for (const v of past) if (!last.has(v.dataset_key)) last.set(v.dataset_key, (Date.now() - new Date(v.at).getTime()) / 864e5);
  if (list) {
    for (const r of races) console.log(`${r.key}: ${r.frames.length} periods (${r.frames[0].period}–${r.frames.at(-1)!.period}), ${raceSeconds(r).toFixed(1)}s, last published ${last.has(r.key) ? `${last.get(r.key)!.toFixed(0)} days ago` : 'never'}`);
    return;
  }
  // The next race: the forced one, or the one that has gone longest without a video (never first).
  const race = forced ? races.find((r) => r.key === forced)
    : [...races].filter((r) => (last.get(r.key) ?? Infinity) >= COOLDOWN_DAYS).sort((a, b) => (last.get(b.key) ?? Infinity) - (last.get(a.key) ?? Infinity))[0];
  if (!race) { console.log(forced ? `No race ${forced}` : 'Every race has a recent video; nothing to do.'); return; }
  console.log(`${race.key}: ${race.title}\n  ${race.captions.map((c) => c.text).join('\n  ') || '(no change of leader)'}`);

  const publicDir = await mkdtemp(join(tmpdir(), 'race-public-'));
  const outDir = await mkdtemp(join(tmpdir(), 'race-out-'));
  try {
    const musicFile = await music(raceSeconds(race), publicDir);
    const files = await render(race, musicFile, publicDir, outDir);

    const { data: buckets } = await db.storage.listBuckets();
    if (!buckets?.some((b) => b.name === BUCKET)) {
      const { error } = await db.storage.createBucket(BUCKET, { public: true });
      if (error) throw new Error(`create bucket: ${error.message}`);
    }
    const today = new Date().toLocaleDateString('en-CA', { timeZone: 'Australia/Sydney' });
    let slug = `${slugify(race.title)}-${today}`;
    if (replace) {
      const { data: live } = await db.from('visuals').select('slug').eq('dataset_key', race.key).eq('status', 'published')
        .order('published_at', { ascending: false }).limit(1).maybeSingle();
      if (!live) throw new Error(`--replace: no published race for ${race.key}`);
      slug = live.slug;
      console.log(`Replacing the videos of /indices/visuals/${slug}`);
    }
    // A dry run uploads to drafts/ (to be watched) and publishes nothing.
    const prefix = dry ? `drafts/${slug}` : slug;
    const videos: Record<string, string> = {};
    for (const [format, file] of Object.entries(files)) {
      const poster = format === 'poster';
      const path = poster ? `${prefix}/poster.jpg` : `${prefix}/${format.replace(':', 'x')}.mp4`;
      const { error } = await db.storage.from(BUCKET).upload(path, await readFile(file), { contentType: poster ? 'image/jpeg' : 'video/mp4', upsert: true });
      if (error) throw new Error(`upload ${path}: ${error.message}`);
      // A version in the link, so a re-render at the same path is never served from a stale CDN or browser cache.
      videos[format] = `${db.storage.from(BUCKET).getPublicUrl(path).data.publicUrl}?v=${Date.now()}`;
    }
    if (dry) { console.log(`Dry run: drafts uploaded, nothing published.\n${Object.entries(videos).map(([f, u]) => `  ${f}: ${u}`).join('\n')}`); return; }
    const lastFrame = race.frames.at(-1)!;
    const rows = Object.entries(lastFrame.values).sort((a, b) => b[1] - a[1]).slice(0, race.topN).map(([code, value]) => ({ label: race.labels[code] ?? code, code, value }));
    // With the production queue on, a new race is a draft until its slot. A re-render of one already published the
    // same day just replaces its videos and stays published.
    const { data: existing } = await db.from('visuals').select('status, published_at').eq('slug', slug).maybeSingle();
    const queueOn = existing?.status !== 'published' && await queueEnabled(db);
    // Upsert: re-rendering a race the same day replaces that day's visual (and its videos, uploaded with upsert).
    const { error } = await db.from('visuals').upsert({
      slug, dataset_key: race.key, template: 'race', title: race.title, subtitle: race.subtitle, takeaways: race.takeaways,
      alt: `Animated bar chart race: ${race.title}. Final standings in ${lastFrame.period}.`,
      spec: { template: 'race', unit: race.unit, measure: race.subtitle, rows, period: lastFrame.period, priorPeriod: race.frames[0].period },
      sources: [race.source], videos, checks: { captions: 'derived from the data, not written by a model', music: musicFile ? (musicIsHouse ? 'Caveat house track' : 'ElevenLabs Music') : 'none' },
      // A re-render of a published race keeps its publication date.
      status: queueOn ? 'draft' : 'published', published_at: queueOn ? null : (existing?.status === 'published' && existing.published_at ? existing.published_at : new Date().toISOString()),
    }, { onConflict: 'slug' });
    if (error) throw new Error(`visuals upsert: ${error.message}`);
    const made = `${Object.keys(videos).filter((k) => k !== 'poster').length} videos and a poster`;
    if (queueOn) {
      await enqueue(db, { kind: 'race', ref_slug: slug, title: race.title, summary: race.takeaways.join(' '), media: videos });
      console.log(`Queued /indices/visuals/${slug} with ${made}.\nScheduling:`);
      await scheduleContent(db);
      await postSocial(db);
    } else console.log(`Published /indices/visuals/${slug} with ${made}.`);
  } finally {
    await rm(publicDir, { recursive: true, force: true });
    await rm(outDir, { recursive: true, force: true });
  }
}

main().catch((e) => { console.error(e); process.exit(1); });
