/**
 * First vintage of home-page instruments. Every observation names a print.
 * Clocks snap to the last official number. Interpolated run-rates are derived
 * in code and labelled as such. Do not add worlddebtclocks-style ticks.
 */
import type { InstrumentObservation, InstrumentSeries } from '@/lib/instrument-types';

function obs(
  period: string,
  value: number,
  status: InstrumentObservation['status'] = 'published',
): InstrumentObservation {
  return { period, value, status };
}

export const INSTRUMENT_SERIES: InstrumentSeries[] = [
  {
    metricId: 'ags_face_value_bn',
    name: 'Australian Government Securities on issue',
    unit: 'AUD billion',
    basis: 'Face value of AGS, not net debt and not market value',
    org: 'Australian Office of Financial Management',
    dataset: 'AGS on issue',
    url: 'https://www.aofm.gov.au/publications/speeches/opening-statement-economics-legislation-committee-1',
    tier: 1,
    observations: [
      obs('2023-06-30', 889.8),
      obs('2024-06-30', 906.9),
      obs('2026-02-11', 994.4),
    ],
  },
  {
    metricId: 'ags_interest_payments_bn',
    name: 'Interest payments on AGS',
    unit: 'AUD billion',
    basis: 'Cash interest payments on Australian Government Securities, Budget Paper 1',
    org: 'Australian Government',
    dataset: 'Budget Paper No. 1, Table 6.9',
    url: 'https://archive.budget.gov.au/2025-26/bp1/download/bp1_bs-6.pdf',
    tier: 1,
    observations: [
      obs('2024-25', 22.666),
      obs('2025-26', 26.303),
    ],
  },
  {
    metricId: 'gst_receipts_bn',
    name: 'GST receipts',
    unit: 'AUD billion',
    basis: 'GST receipts, Budget Paper No. 3',
    org: 'Australian Government',
    dataset: 'Budget Paper No. 3, GST',
    url: 'https://archive.budget.gov.au/2025-26/bp3/download/bp3_13_part_3.pdf',
    tier: 1,
    observations: [
      obs('2024-25', 89.4),
      obs('2025-26', 94.234),
    ],
  },
  {
    metricId: 'gdp_nominal_aud_bn',
    name: 'Nominal GDP',
    unit: 'AUD billion',
    basis: 'Implied from Budget Paper 1 total receipts as a share of GDP',
    org: 'Australian Government',
    dataset: 'Budget Paper No. 1 receipts as per cent of GDP',
    url: 'https://archive.budget.gov.au/2025-26/bp1/download/bp1_bs-4.pdf',
    tier: 1,
    observations: [
      obs('2024-25', 2782, 'derived'),
      obs('2025-26', 2884, 'derived'),
    ],
  },
  {
    metricId: 'household_credit_bn',
    name: 'Household credit outstanding',
    unit: 'AUD billion',
    basis: 'RBA Lending and Credit Aggregates D2, household credit, monthly',
    org: 'Reserve Bank of Australia',
    dataset: 'Statistical table D2',
    url: 'https://www.rba.gov.au/statistics/tables/xls/d02hist.xlsx',
    tier: 1,
    observations: [
      obs('2025-11', 2469.49),
      obs('2025-12', 2487.29),
      obs('2026-01', 2497.93),
      obs('2026-02', 2508.16),
      obs('2026-03', 2522.64),
      obs('2026-04', 2536.04),
      obs('2026-05', 2549.34),
      obs('2026-06', 2568.43),
    ],
  },
  {
    metricId: 'erp_persons',
    name: 'Estimated resident population',
    unit: 'persons',
    basis: 'ABS estimated resident population at quarter end',
    org: 'Australian Bureau of Statistics',
    dataset: 'National, state and territory population',
    url: 'https://www.abs.gov.au/statistics/people/population/national-state-and-territory-population/latest-release',
    tier: 1,
    observations: [
      obs('2025-06-30', 27_614_411),
      obs('2025-12-31', 27_801_023),
    ],
  },
  {
    metricId: 'nom_annual',
    name: 'Net overseas migration',
    unit: 'persons',
    basis: 'Year ended December, ABS preliminary',
    org: 'Australian Bureau of Statistics',
    dataset: 'National, state and territory population',
    url: 'https://www.abs.gov.au/statistics/people/population/national-state-and-territory-population/latest-release',
    tier: 1,
    observations: [
      obs('2022', 437_857),
      obs('2023', 530_620),
      obs('2024', 330_458),
      obs('2025', 300_955),
    ],
  },
  {
    metricId: 'natural_increase_annual',
    name: 'Natural increase',
    unit: 'persons',
    basis: 'Births minus deaths, year ended December, ABS preliminary',
    org: 'Australian Bureau of Statistics',
    dataset: 'National, state and territory population',
    url: 'https://www.abs.gov.au/statistics/people/population/national-state-and-territory-population/latest-release',
    tier: 1,
    observations: [
      obs('2022', 108_633),
      obs('2023', 105_755),
      obs('2024', 101_411),
      obs('2025', 111_539),
    ],
  },
  {
    metricId: 'population_growth_annual',
    name: 'Population growth',
    unit: 'persons',
    basis: 'Year ended December, ABS preliminary',
    org: 'Australian Bureau of Statistics',
    dataset: 'National, state and territory population',
    url: 'https://www.abs.gov.au/statistics/people/population/national-state-and-territory-population/latest-release',
    tier: 1,
    observations: [
      obs('2022', 546_490),
      obs('2023', 636_375),
      obs('2024', 431_869),
      obs('2025', 412_494),
    ],
  },
  {
    metricId: 'dwelling_completions',
    name: 'Dwelling completions',
    unit: 'dwellings',
    basis: 'Total sector dwelling completions, seasonally adjusted',
    org: 'Australian Bureau of Statistics',
    dataset: 'Building Activity, Australia',
    url: 'https://www.abs.gov.au/statistics/industry/building-and-construction/building-activity-australia/dec-2025',
    tier: 1,
    observations: [
      obs('2024-Q4', 45_167),
      obs('2025-Q1', 43_517),
      obs('2025-Q2', 40_524),
      obs('2025-Q3', 44_242),
      obs('2025-Q4', 43_536),
    ],
  },
  {
    metricId: 'dwelling_stock_value_bn',
    name: 'Total value of residential dwellings',
    unit: 'AUD billion',
    basis: 'ABS Total Value of Dwellings, Australia',
    org: 'Australian Bureau of Statistics',
    dataset: 'Total Value of Dwellings',
    url: 'https://www.abs.gov.au/media-centre/media-releases/value-dwellings-falls-03',
    tier: 1,
    observations: [
      obs('2021-Q2', 8726),
      obs('2021-Q3', 9326),
      obs('2021-Q4', 9914),
      obs('2022-Q1', 10094),
      obs('2022-Q2', 10029),
      obs('2022-Q3', 9730),
      obs('2022-Q4', 9773),
      obs('2023-Q1', 9803),
      obs('2023-Q2', 10102),
      obs('2023-Q3', 10253),
      obs('2023-Q4', 10564),
      obs('2024-Q1', 10736),
      obs('2024-Q2', 11000),
      obs('2024-Q3', 11053),
      obs('2024-Q4', 11319),
      obs('2025-Q1', 11409),
      obs('2025-Q2', 11697),
      obs('2025-Q3', 11978),
      obs('2025-Q4', 12509),
      obs('2026-Q1', 12723),
      obs('2026-Q2', 12689),
    ],
  },
  {
    metricId: 'mean_dwelling_price',
    name: 'Mean dwelling price',
    unit: 'AUD',
    basis: 'ABS mean price of residential dwellings, Australia',
    org: 'Australian Bureau of Statistics',
    dataset: 'Total Value of Dwellings',
    url: 'https://www.abs.gov.au/media-centre/media-releases/value-dwellings-falls-03',
    tier: 1,
    observations: [
      obs('2026-Q2', 1_100_000),
    ],
  },
];
